[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "cairosvg>=2.7.1",
    "lxml>=5.3.2",
    "openpyxl==3.1.5",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
